### ISSUE TITLE
/f show Issue // Internal error 

### ISSUE THREAD

**Issue by Fetish11** [redstone/LegacyFactions#255]
Hello, just installed LegacyFactions and when I run f show I get this error

Debug - https://gyazo.com/895300300cd689e1f534d7a1171bd293

[19:48:10 INFO]: ***Hello <Fetish> t
[19:48:11 INFO]: Fetish issued server command: /f show
[19:48:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' i
n plugin LegacyFactions v1.4.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[pap
er.jar:git-Paper-1104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:15
1) ~[paper.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServ
er.java:675) ~[paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerCo
nnection.java:1393) ~[paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.jav
a:1198) ~[paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:45) ~[paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:5) ~[paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMain
Thread$0(PlayerConnectionUtils.java:14) ~[paper.jar:git-Paper-1104]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [paper.jar
:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:
839) [paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:
403) [paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:
763) [paper.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.jav
a:661) [paper.jar:git-Paper-1104]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at net.redstoneore.legacyfactions.integration.vault.util.VaultUtilPlayer
.getFriendlyBalance(VaultUtilPlayer.java:21) ~[?:?]
        at net.redstoneore.legacyfactions.integration.vault.util.VaultUtilPlayer
.getFriendlyBalance(VaultUtilPlayer.java:30) ~[?:?]
        at net.redstoneore.legacyfactions.util.TagReplacerUtil.getValue(TagRepla
cerUtil.java:167) ~[?:?]
        at net.redstoneore.legacyfactions.util.TagUtil.parsePlain(TagUtil.java:7
2) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsShow.perform(CmdFaction
sShow.java:70) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:118
) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46)
 ~[?:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:104
) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46)
 ~[?:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:122
) ~[?:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(Facti
onsPluginBase.java:184) ~[?:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(Facti
onsPluginBase.java:147) ~[?:?]
        at net.redstoneore.legacyfactions.Factions.handleCommand(Factions.java:2
31) ~[?:?]
        at net.redstoneore.legacyfactions.Factions.onCommand(Factions.java:240)
~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[pap
er.jar:git-Paper-1104]
        ... 15 more
>

**Comment by MarkehMe** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by Fetish11** [comment]
version https://gyazo.com/fa3302e280521fac9dc20160ea308263

**Comment by Fetish11** [comment]
conf - https://pastebin.com/YxFJYYvb

**Comment by MarkehMe** [comment]
You're LegacyFactions version is 1.4.1. Please update.
