### ISSUE TITLE
This error i have got after NPC-Sentinel hit a mob on a faction territory

### ISSUE THREAD

**Issue by Fortepsai** [redstone/LegacyFactions#260]
[00:23:36 ERROR]: Could not pass event PlayerInteractEvent to LegacyFactions v1.4.7
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateWeighted.e(BlockPressurePlateWeighted.java:32) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:951) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:534) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.EntityHuman.g(EntityHuman.java:1441) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.g(EntityHumanNPC.java:233) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:360) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:134) [Citizens.jar:?]
at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:1010) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.tick(NMS.java:294) [Citizens.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens.jar:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
at net.redstoneore.legacyfactions.mixin.PlayerMixin.getItemInMainHand(PlayerMixin.java:60) ~[?:?]
at net.redstoneore.legacyfactions.entity.persist.memory.MemoryFPlayer.getItemInMainHand(MemoryFPlayer.java:131) ~[?:?]
at net.redstoneore.legacyfactions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:405) ~[?:?]
at net.redstoneore.legacyfactions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:268) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
... 26 more
[00:23:36 ERROR]: Could not pass event PlayerInteractEvent to LegacyFactions v1.4.7
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateWeighted.e(BlockPressurePlateWeighted.java:32) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:951) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:534) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.EntityHuman.g(EntityHuman.java:1441) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.g(EntityHumanNPC.java:233) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:360) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:134) [Citizens.jar:?]
at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:1010) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.tick(NMS.java:294) [Citizens.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens.jar:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
at net.redstoneore.legacyfactions.mixin.PlayerMixin.getItemInMainHand(PlayerMixin.java:60) ~[?:?]
at net.redstoneore.legacyfactions.entity.persist.memory.MemoryFPlayer.getItemInMainHand(MemoryFPlayer.java:131) ~[?:?]
at net.redstoneore.legacyfactions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:405) ~[?:?]
at net.redstoneore.legacyfactions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:268) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
... 26 more
[00:23:36 ERROR]: Could not pass event PlayerInteractEvent to LegacyFactions v1.4.7
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateWeighted.e(BlockPressurePlateWeighted.java:32) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:951) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:534) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.EntityHuman.g(EntityHuman.java:1441) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.g(EntityHumanNPC.java:233) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:360) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:134) [Citizens.jar:?]
at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:1010) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.tick(NMS.java:294) [Citizens.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens.jar:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
at net.redstoneore.legacyfactions.mixin.PlayerMixin.getItemInMainHand(PlayerMixin.java:60) ~[?:?]
at net.redstoneore.legacyfactions.entity.persist.memory.MemoryFPlayer.getItemInMainHand(MemoryFPlayer.java:131) ~[?:?]
at net.redstoneore.legacyfactions.listeners.FactionsPlayerListener.canPlayerUseBlock(FactionsPlayerListener.java:405) ~[?:?]
at net.redstoneore.legacyfactions.listeners.FactionsPlayerListener.onPlayerInteract(FactionsPlayerListener.java:268) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]

**Comment by Fortepsai** [comment]
[00:33:17 INFO]: === START DEBUG ===
[00:33:17 INFO]:
[00:33:17 INFO]: ----- Server Information -----
[00:33:17 INFO]: Server Version: git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
[00:33:17 INFO]: LegacyFactions v1.4.7
[00:33:17 INFO]: Package: package java.lang, Java Platform API Specification, version 1.8
[00:33:17 INFO]: Java Version: 1.8.0_74
[00:33:17 INFO]:
[00:33:17 INFO]:
[00:33:17 INFO]: ----- Plugins -----
[00:33:17 INFO]: dynmap v2.5-Dev201706100405 by mikeprimm
[00:33:17 INFO]: WorldEdit v6.1.8-SNAPSHOT;cd4729f by
[00:33:17 INFO]: CCcooldowns v1.0 by WPM
[00:33:17 INFO]: iConomy_Recreation v8.0 by moloco
[00:33:17 INFO]: PlaceholderAPI v2.8.2 by [extended_clip]
[00:33:17 INFO]: MythicLib v0.0.1-SNAPSHOT by Xikage AKA Ashijin
[00:33:17 INFO]: ClearLag v2.9.7 by bob7l
[00:33:17 INFO]: sTablist v3.0.0-pre1 by Jul1an_K
[00:33:17 INFO]: ChatControl v5.6.1 by kangarko
[00:33:17 INFO]: WorldBorder v1.8.6 by Brettflan
[00:33:17 INFO]: EPearlCooldown v4.0 by JMAK
[00:33:17 INFO]: Multiverse-Core v2.5-b719 by Rigby, fernferret, lithium3141, main--
[00:33:17 INFO]: ProtocolLib v4.3.0 by dmulloy2, comphenix
[00:33:17 INFO]: WorldGuard v6.1.3-SNAPSHOT;c904242 by
[00:33:17 INFO]: LibsDisguises v9.5.0 by libraryaddict, Byteflux, Navid K.
[00:33:17 INFO]: InfinityDispensers v1.2 by Ablax
[00:33:17 INFO]: MultiWorld v5.2.8 by ferrybig
[00:33:17 INFO]: SkinsRestorer v12.8.1 by Blackfire62,Th3Tr0LLeR
[00:33:17 INFO]: EnchantLimit v2.2 by BladeFireTurtle
[00:33:17 INFO]: StrengthFix v1.0.0 by Genex
[00:33:17 INFO]: GoldenAppleControl v2.0.5 by Terrobility
[00:33:17 INFO]: CreeperHeal v7.0.4 by nitnelave
[00:33:17 INFO]: DispenserTools v2.0 by slowbuild
[00:33:17 INFO]: Vault v1.6.1 by cereal, Sleaker, mung3r
[00:33:17 INFO]: FakaHedaMinequery v1.7 by
[00:33:17 INFO]: Cannons v2.4.5 by DerPavlov
[00:33:17 INFO]: ArmorWeight v0.3.12 by Zettelkasten
[00:33:17 INFO]: Essentials v2.0.1-bSNAPSHOT by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685
[00:33:17 INFO]: HolographicDisplays v2.2.6 by
[00:33:17 INFO]: LegacyFactions v1.4.7 by Cayorion, Madus, Ulumulu1510, MarkehMe, Brettflan, drtshock
[00:33:17 INFO]: AdvanceRespawn v6.1.3 by Matan Rak
[00:33:17 INFO]: Citizens v2.0.22-SNAPSHOT (build 1493) by aPunch, fullwall
[00:33:17 INFO]: MythicMobs v4.3.2-SNAPSHOT by Xikage AKA Ashijin
[00:33:17 INFO]: Quests v3.0.0-Naomi-b${env.BUILD_NUMBER} by Blackvein, HappyPikachu
[00:33:17 INFO]: EssentialsProtect v2.0.1-bSNAPSHOT by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
[00:33:17 INFO]: Duels v1.3.4 by Realized
[00:33:17 INFO]: Shop v2.1.0 by Conjurate
[00:33:17 INFO]: MLGDamageIndicators v1.2 by RoboMWM
[00:33:17 INFO]: EssentialsSpawn v2.0.1-bSNAPSHOT by Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits
[00:33:17 INFO]: PvPManager v3.3.3.2 by NoChanceSD
[00:33:17 INFO]: CitizensText v1.7 by SkytAsul
[00:33:17 INFO]: FactionScoreboard v3.0 by [Luke Kander]
[00:33:17 INFO]: Sentinel v1.4.5 (build 155) by mcmonkey
[00:33:17 INFO]: MythicArtifacts v0.1.12-SNAPSHOT by Xikage AKA Ashijin
[00:33:17 INFO]:
[00:33:17 INFO]: ----- Integrations -----
[00:33:17 INFO]: Vault = true
[00:33:17 INFO]: WorldGuard = true
[00:33:17 INFO]: Essentials = true
[00:33:17 INFO]: Metrics = true
[00:33:17 INFO]: bStats = true
[00:33:17 INFO]: Dynmap = true
[00:33:17 INFO]:
[00:33:17 INFO]: === END DEBUG ===

**Comment by markhughes** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by markhughes** [comment]
Thanks, I'll look into this.

**Comment by Fortepsai** [comment]
and one more thing it happens always when it hit my MythicMob craeted mob .
