### ISSUE TITLE
LegacyFactions Crashing Server on startup.

### ISSUE THREAD

**Issue by Xrey274** [redstone/LegacyFactions#91]
Latest_log(without LegacyFactions) - https://www.dropbox.com/s/tk0g2ebngmqrkm7/latest.log?dl=0
Latest_log(with LegacyFactions) - https://www.dropbox.com/s/7wids7t96q0nl0n/latest_with.log?dl=0
Latest Crash(with LegacyFactions) - https://www.dropbox.com/s/1uxhpouqbvy0qdf/crash-2017-08-06_11.51.09-server.txt?dl=0
conj.json - https://www.dropbox.com/s/wy4idgrfmyhycum/conf.json?dl=0
Bukkit_Version - 1.8-R0.1-Snapshot
LegacyFactions_Version - 1.4

**Comment by MarkehMe** [comment]
If you read your crash log you will see the stack trace:

```

-- Head --
Stacktrace:
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at me.poutineqc.mentionnotifier.IgnoreList.isLastVersion(IgnoreList.java:77)
	at me.poutineqc.mentionnotifier.IgnoreList.access$2(IgnoreList.java:72)
	at me.poutineqc.mentionnotifier.IgnoreList$1.run(IgnoreList.java:54)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:668)
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)

```

The reason it occurs with LegacyFactions installed is because [MentionNotifier](https://www.spigotmc.org/resources/mention-notifier.20485/) is not starting up without LegacyFactions installed - as LegacyFactions uses gson, but we have shadowed it into the binary. As you can see in your log without LegacyFaction it has not found shaded/shadowed this library:

```
[11:55:08] [Server thread/INFO]: [MN] Enabling MentionNotifier v1.2.2
[11:55:08] [Server thread/ERROR]: Error occurred while enabling MentionNotifier v1.2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/JsonElement
	at me.poutineqc.mentionnotifier.hook.ProtocolLibHandeler.reload(ProtocolLibHandeler.java:23) ~[?:?]
	at me.poutineqc.mentionnotifier.MentionNotifier.onEnable(MentionNotifier.java:29) ~[?:?]
...
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
...```

Please remove MentionNotifier because it is not working either way, and ask the developer there.

Good luck!
