### ISSUE TITLE
Some Problem,sorry about that,my english is low

### ISSUE THREAD

**Issue by leinouwo** [redstone/LegacyFactions#99]
```
 Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[物品炫耀ShowOffW.jar:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) [物品炫耀ShowOffW.jar:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:682) [物品炫耀ShowOffW.jar:?]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.perform(CmdFactionsHelp.java:147) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:118) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:104) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:122) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:184) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:147) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.handleCommand(Factions.java:231) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.onCommand(Factions.java:236) [阵营LegacyFactions.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[10:57:57 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:682) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.lambda$perform$1(CmdFactionsHelp.java:150) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_131]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.perform(CmdFactionsHelp.java:149) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:118) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:104) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:122) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:184) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:147) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.handleCommand(Factions.java:231) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.onCommand(Factions.java:236) [阵营LegacyFactions.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[10:57:57 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:682) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.lambda$perform$1(CmdFactionsHelp.java:150) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_131]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.perform(CmdFactionsHelp.java:149) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:118) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:104) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:122) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:184) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:147) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.handleCommand(Factions.java:231) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.onCommand(Factions.java:236) [阵营LegacyFactions.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[10:57:57 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:682) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.lambda$perform$1(CmdFactionsHelp.java:150) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_131]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.perform(CmdFactionsHelp.java:149) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:118) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:104) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:122) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:184) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:147) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.handleCommand(Factions.java:231) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.onCommand(Factions.java:236) [阵营LegacyFactions.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[10:57:57 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_131]
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) ~[?:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:682) ~[?:?]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.lambda$perform$1(CmdFactionsHelp.java:150) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_131]
        at net.redstoneore.legacyfactions.cmd.CmdFactionsHelp.perform(CmdFactionsHelp.java:149) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:118) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:104) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.FCommand.execute(FCommand.java:46) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.cmd.MCommand.execute(MCommand.java:122) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:184) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.FactionsPluginBase.handleCommand(FactionsPluginBase.java:147) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.handleCommand(Factions.java:231) [阵营LegacyFactions.jar:?]
        at net.redstoneore.legacyfactions.Factions.onCommand(Factions.java:236) [阵营LegacyFactions.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
```

**Comment by MarkehMe** [comment]
Please share:

1) your conf.json file
2) the output of  the `/f debug` command (run from console)
